version: '3.4'
services:
  db:
    image: mysql:5.7.22
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin123
      MYSQL_DATABASE: pet-schedule
    ports:
      - "3306:3306"
    expose:
      - "3306" 
    volumes:
      - "/home/data/datadir/pet-schedule:/var/lib/mysql"
    networks:
      - myEnv-network
  docker-from-pet-schedule-java:
    image: docker-from-pet-schedule-java
    restart: always
    build:
      context: .
      dockerfile: app/Dockerfile
    working_dir: /app
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8080:8080" 
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - myEnv-network
networks:
    myEnv-network:
        driver: bridge